#!/usr/bin/env node

/**
 * MrFabric CLI Wrapper - Standalone executable
 * Make script executable: chmod +x ./mr-fabric-import
 * Usage: ./mr-fabric-import ./images --preview
 */

const path = require('path')
const { execSync } = require('child_process')

const scriptPath = path.join(__dirname, 'scripts', 'batchImport.js')
const args = process.argv.slice(2)

try {
  execSync(`node "${scriptPath}" ${args.join(' ')}`, { stdio: 'inherit' })
} catch (err) {
  process.exit(1)
}
